### ISSUE TITLE
Can not build on ubuntu 22.04.3

### ISSUE THREAD

**Issue by cryptocj** [ordinals/ord#3384]
```
cargo build --release
   Compiling ord v0.16.0
error[E0658]: use of unstable library feature 'result_option_inspect'
   --> src/index/updater/rune_updater.rs:153:10
    |
153 |         .inspect(|&pointer| assert!(pointer < allocated.len()))
    |          ^^^^^^^
    |
    = note: see issue #91345 <https://github.com/rust-lang/rust/issues/91345> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `ord` (lib) due to previous error
```

**Comment by cryptocj** [comment]
chatgpt advices to use
```
   rustup install nightly
   rustup default nightly
```

is this a good choice? buy anyway  I can build now.

**Comment by markovichecha** [comment]
Update to rust 1.77.0, use something like rustup, ubuntu repositories have an old rust version 1.75.0

**Comment by cryptocj** [comment]
thanks, but I'm using 1.79.0
```
rustc --version
rustc 1.79.0-nightly (47ecded35 2024-03-26)
```

**Comment by markovichecha** [comment]
> thanks, but I'm using 1.79.0
> 
> ```
> 
> rustc --version
> 
> rustc 1.79.0-nightly (47ecded35 2024-03-26)
> 
> ```

Yes, because you switched to nightly. It may be unstable to use in production. If you want ord to work on stable version, update it to 1.76.0 or higher version.
