### ISSUE TITLE
unable to build 0.21.3 for Windows - temporary value dropped while borrowed  

### ISSUE THREAD

**Issue by cryptoni9n** [ordinals/ord#4073]
receiving these errors when trying to `cargo build --release` from git branch 0.21.3:

```bash
error[E0716]: temporary value dropped while borrowed                                                                                                               
  --> src\subcommand\verify.rs:35:8
   |
34 |       } else if let Some(file) = &self.file {
   |  ____________-
35 | |       &fs::read(file)?
   | |        ^^^^^^^^^^^^^^^ creates a temporary value which is freed while still in use
36 | |     } else {
   | |     - temporary value is freed at the end of this statement
37 | |       unreachable!()
38 | |     };
   | |_____- borrow later used here
   |
   = note: consider using a `let` binding to create a longer lived value

error[E0716]: temporary value dropped while borrowed
  --> src\subcommand\wallet\sign.rs:38:8
   |
37 |       } else if let Some(file) = &self.file {
   |  ____________-
38 | |       &fs::read(file)?
   | |        ^^^^^^^^^^^^^^^ creates a temporary value which is freed while still in use
39 | |     } else {
   | |     - temporary value is freed at the end of this statement
40 | |       unreachable!()
41 | |     };
   | |_____- borrow later used here
   |
   = note: consider using a `let` binding to create a longer lived value

For more information about this error, try `rustc --explain E0716`.
error: could not compile `ord` (lib) due to 2 previous errors
```

**Comment by so7ow** [comment]
Works fine for me on Linux with rustc v1.82. Got current/recent rust toolkit?

```
$ rustc --version
rustc 1.82.0 (f6e511eec 2024-10-15)
```

**Comment by dcorral** [comment]
I had the same issue with rustc 1.77.2, upgrading to rustc 1.82.0 fixes this. 

```bash
rustup upgrade
cargo clean
cargo build --release
```

**Comment by cryptoni9n** [comment]
> For whatever it's worth: works fine for me on Ubuntu with rustc v1.82. Got current/recent rust toolkit?
> 
> ```
> $ rustc --version
> rustc 1.82.0 (f6e511eec 2024-10-15)
> ```

thanks @so7ow - you are correct.  I was on 1.77.0 and was able to build successfully after upgrading to 1.82.0.  I think Cargo.toml needs to have  the `rust-version` updated.

**Comment by raphjaph** [comment]
Thanks good catch! https://github.com/ordinals/ord/issues/4073
