### ISSUE TITLE
Error introduced in 0.12.1: fn fund_raw_transaction can't leak private type FundRawTransactionOptions` declared as private

### ISSUE THREAD

**Issue by roadbuilder** [ordinals/ord#2792]
https://github.com/ordinals/ord/blame/bb43a9dccbd317ebb93c7753ead39f23084b1656/test-bitcoincore-rpc/src/api.rs#L54

Staring with tag release 0.12.1 this error won't allow the tests to complete; the error is also in 0.12.2; maybe run the tests before pushing out new tagged releases?

```
cargo test
   Compiling ord v0.12.1 
   Compiling test-bitcoincore-rpc v0.0.1
error[E0446]: private type `FundRawTransactionOptions` in public interface
   --> test-bitcoincore-rpc\src\api.rs:54:3
    |
54  | /   fn fund_raw_transaction(
55  | |     &self,
56  | |     tx: String,
57  | |     options: Option<FundRawTransactionOptions>,
58  | |     is_witness: Option<bool>,
59  | |   ) -> Result<FundRawTransactionResult, jsonrpc_core::Error>;
    | |_____________________________________________________________^ can't leak private type
    |
   ::: test-bitcoincore-rpc\src\lib.rs:162:1
    |
162 |   struct FundRawTransactionOptions {
    |   -------------------------------- `FundRawTransactionOptions` declared as private
```

**Comment by casey** [comment]
> Staring with tag release 0.12.1 this error won't allow the tests to complete; the error is also in 0.12.2; 

I can't reproduce this. `cargo test` works on my machine for both 0.12.1 and 0.12.2. To reproduce, do I need to do anything other than check out 0.12.1 and run `cargo test`?

> maybe run the tests before pushing out new tagged releases?

Don't be rude.

**Comment by roadbuilder** [comment]
Sorry for being rude, I'm on my period.. j/k

Yeah, I just checked again, cloned code, git checkout 0.12.1, cargo test, and same error; cargo build works fine. This is windows system, going to try on linux and mac. 

Nope, fresh clone on linux, checkout 0.12.1, same error: can't leak private type, no error on 0.12.0; same error on 0.12.2 and 0.12.3

On brand new super powerful virgin mac, installed rust, git, did a clone of the repo, git checkout 0.12.1, cargo test.. didn't get that same error.  However getting other failed tests on mac, for even version 0.12.0 .. the plot thickens... 

I'll keep poking around see if I can figure out a fix

**Comment by roadbuilder** [comment]
ah okay.. looks like it is due to ord-bitcoincore-rpc being changed from "0.17.0" to "0.17.1"; so probably an issue for the ord-bitcoincore-rpc project: https://github.com/ordinals/rust-bitcoincore-rpc/commit/55c54dbafc4b2ef0fb3a37a0b86efbf0eaaa7235

When I change the test-bitcoincore-rpc/Cargo.toml back to ord-bitcoincore-rpc = "0.17.0", then cargo test on 0.12.1 on doesn't have get the same error.

Looks like problem was created in 0.12.1 here: https://github.com/ordinals/ord/blame/0.12.1/test-bitcoincore-rpc/src/lib.rs#L162

Adding "pub" in front of it should fix it:
pub struct FundRawTransactionOptions {

**Comment by roadbuilder** [comment]
Changing that to pub now gives another error when running tests: 

```
cargo test
   Compiling test-bitcoincore-rpc v0.0.1
   Compiling ord v0.12.3
error[E0574]: expected struct, variant or union type, found trait `Output`
  --> src\subcommand\wallet\balance.rs:61:30
   |
61 |       serde_json::to_string(&Output {
   |                              ^^^^^^ not a struct, variant or union type
   |
help: consider importing one of these items instead
   |
56 +   use bitcoin::psbt::Output;
   |
56 +   use crate::process::Output;
   |
56 +   use crate::subcommand::balances::Output;
   |
56 +   use crate::subcommand::decode::Output;
   |
     and 19 other candidates

For more information about this error, try `rustc --explain E0574`.
error: could not compile `ord` (lib test) due to previous error
warning: build failed, waiting for other jobs to finish...
```

Seems to be related to that same commit: https://github.com/ordinals/ord/blame/0b4d7af93e6005620c1efe6aa6df21361728c1cc/src/subcommand/wallet/balance.rs#L59

**Comment by roadbuilder** [comment]
> Thanks for digging into this! I started looking at it, and I couldn't make sense of why it would be happening, so I'm relieved that it's a compiler issue.

thank you!  actually no problem with your code, just a problem with the compiler..  1.73.0 version couldn't see the Output struct when it really was coded correctly, nothing wrong with the code
